# .github/workflows/build.yml
# Compile LaTeX documents
# See https://github.com/xu-cheng/latex-action for details

name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run:
    name: Compile LaTeX documents
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate PDF documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
          args: -file-line-error -halt-on-error -interaction=nonstopmode
          extra_fonts: |
            ./fonts/fira-mono/*.otf
            ./fonts/fira-sans/*.otf
          pre_compile: tlmgr update --self && tlmgr update --all
          latexmk_shell_escape: true

      - name: Rename PDF documents
        run: bash build_tools/github/rename.sh

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          path: "*.pdf"
          if-no-files-found: error
